spring.application.name=calculator-backend
server.port=8080

spring.datasource.url=jdbc:sqlite:calculator.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.datasource.hikari.maximum-pool-size=1

spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql

server.error.include-message=never
